"""Golden CO — Bergen catchall × 4 substrate matrix apply.

Pre-stage source: backend/data/wave6_pre_stage/jefferson_golden.json
Owner: orchestrator
Generated by: backend/scripts/_drafts/_wave6_apply_generator.py
Pattern: Bergen catchall × 4 prohibited substrate-first per halt rule.

CRITICAL — fire gate per Master 2026-06-23 dispatch:
- Lane A's Class B zoning adapter MUST RUN against prod first
- parcels.zoning_code must be populated (cov ≥ 70%)
- This script then adapts pre-stage codes to prod spellings (Winnetka
  lesson: pre-stage R-1 → prod R1) and POSTs the matrix substrate
- Substrate-first only — NO verdict-truth lifts (halted Somerset domain)

Apply workflow:
1. Query /api/admin/op5/uncovered-zone-codes for actual prod zone codes
2. Spelling-adapt pre-stage substrate to match prod (drop unmatched,
   rename hyphen-variants)
3. POST to /api/jurisdictions/{JID}/_upload-matrix-rows with
   replace_existing=False (factory_safe_write contract preserves
   nache's human_reviewed=true rows)
4. Verify uncovered_count → 0
5. Trigger ONE refresh

Usage:
    export GOLDEN_CO_JID=<jurisdiction_uuid>  # resolve from prod
    python backend/scripts/_apply_golden_co.py

Exit codes: 0 = success / 1 = apply failed / 2 = JID not set / 3 = no codes to match
"""
from __future__ import annotations
import json
import os
import sys
from pathlib import Path

import httpx

# === CONFIGURATION ===
MUNI = "Golden"
STATE = "CO"

# JID resolution priority:
#   1. GOLDEN_CO_JID environment variable (set at fire-time)
#   2. KNOWN_JID hardcoded below (only if jurisdiction already registered
#      in prod per 2026-06-23 probe; otherwise empty string)
KNOWN_JID = ""  # NOT REGISTERED in prod per 2026-06-23 probe; set GOLDEN_CO_JID env var at fire-time

JID = os.environ.get("GOLDEN_CO_JID") or KNOWN_JID

API_BASE = "https://capable-serenity-production-0d1a.up.railway.app"
PRESTAGE_PATH = (
    Path(__file__).resolve().parent.parent
    / "data" / "wave6_pre_stage" / "jefferson_golden.json"
)
REFRESH_SOURCE = "wave6-prestage-golden-2026-06-23"
# === END CONFIGURATION ===


def fetch_prod_zone_codes(jid: str) -> tuple[set[str], int]:
    """Return (uncovered_zone_codes_set, total_uncovered_count)."""
    url = f"{API_BASE}/api/admin/op5/uncovered-zone-codes"
    params = {"jurisdiction_id": jid, "limit": 500}
    r = httpx.get(url, params=params, timeout=60.0)
    r.raise_for_status()
    body = r.json()
    codes = {row["zone_code"] for row in body.get("rows", []) if row.get("zone_code")}
    return codes, body.get("uncovered_count", 0)


def spelling_variants(code: str) -> list[str]:
    """Generate common spelling variants to try against prod (Winnetka pattern)."""
    out = [code]
    # Hyphen <-> no-hyphen (Winnetka: R-1 vs R1)
    out.append(code.replace("-", ""))
    out.append(code.replace("-", " "))
    # Period <-> no-period (e.g., R-.05 vs R-05)
    out.append(code.replace(".", ""))
    # Lowercase (rare but possible)
    out.append(code.lower())
    out.append(code.upper())
    # Strip whitespace variants
    out.append(code.replace(" ", ""))
    out.append(code.replace(" ", "-"))
    # De-duplicate while preserving order
    seen = set()
    result = []
    for v in out:
        if v not in seen:
            seen.add(v)
            result.append(v)
    return result


def adapt_codes(prestage_rows: list[dict], prod_codes: set[str]) -> tuple[list[dict], list[str], list[str]]:
    """Adapt pre-stage rows to match prod code spellings.
    Returns (adapted_rows, missing_pre_codes, unused_prod_codes).
    """
    adapted = []
    missing = []
    matched_prod = set()
    for row in prestage_rows:
        pre_code = row["zone_code"]
        match = None
        for variant in spelling_variants(pre_code):
            if variant in prod_codes:
                match = variant
                break
        if match is None:
            missing.append(pre_code)
            continue
        new_row = dict(row)
        new_row["zone_code"] = match
        adapted.append(new_row)
        matched_prod.add(match)
    unused = sorted(prod_codes - matched_prod)
    return adapted, missing, unused


def main() -> int:
    print(f"{MUNI} {STATE} matrix substrate apply")
    print(f"  pre-stage: {PRESTAGE_PATH}")
    if not JID:
        print(
            f"ERROR: JID not set. Either populate KNOWN_JID at top of file "
            f"or set env var GOLDEN_CO_JID to a jurisdiction UUID.",
            file=sys.stderr,
        )
        return 2

    print(f"  jurisdiction_id: {JID}")
    upload_url = f"{API_BASE}/api/jurisdictions/{JID}/_upload-matrix-rows"
    refresh_url = (
        f"{API_BASE}/api/admin/coverage/refresh"
        f"?jurisdiction_id={JID}&source={REFRESH_SOURCE}"
    )

    prestage_rows = json.loads(PRESTAGE_PATH.read_text())
    print(f"  pre-stage rows: {len(prestage_rows)}")

    print(f"\nFetching prod uncovered codes")
    prod_codes, uncov_count = fetch_prod_zone_codes(JID)
    print(f"  uncovered_count: {uncov_count}")
    print(f"  distinct uncovered codes: {len(prod_codes)}")

    if not prod_codes:
        print(
            f"\nNo uncovered codes in prod. Either:\n"
            f"  (a) jurisdiction fully matrix-covered already, or\n"
            f"  (b) parcels.zoning_code not yet populated (cov gate fail).\n"
            f"Verify cov gate via /api/admin/coverage before re-running.",
            file=sys.stderr,
        )
        return 3

    adapted, missing, unused = adapt_codes(prestage_rows, prod_codes)
    print(f"\nCode adaptation:")
    print(f"  adapted (matched prod): {len(adapted)}")
    if missing:
        print(f"  WARNING — pre-stage codes NOT found in prod: {missing}")
    if unused:
        print(f"  NOTE — prod codes NOT in pre-stage (substrate gap, "
              f"may need Path B re-author): {unused}")

    if not adapted:
        print(f"\nNo codes matched. Substrate fully out of sync with prod.\n"
              f"Re-author substrate using Path B pattern.", file=sys.stderr)
        return 3

    payload = {"rows": adapted, "replace_existing": False}
    print(f"\nPOST {upload_url}")
    print(f"  rows={len(adapted)}  replace_existing=False  "
          f"factory_safe_write=preserves human_reviewed=true rows")
    r = httpx.post(upload_url, json=payload, timeout=120.0)
    print(f"\nHTTP {r.status_code}")
    try:
        body = r.json()
        print(json.dumps(body, indent=2)[:3000])
    except Exception:
        print(r.text[:3000])

    if r.status_code != 200:
        print(f"\nApply failed (HTTP {r.status_code}). NOT firing refresh.",
              file=sys.stderr)
        return 1

    # Verify uncovered_count post-apply
    print(f"\nVerifying post-apply state")
    _, post_uncov = fetch_prod_zone_codes(JID)
    print(f"  uncovered_count post-apply: {post_uncov} "
          f"(was {uncov_count}; delta -{uncov_count - post_uncov})")

    # ONE refresh per polygon
    print(f"\nPOST {refresh_url}")
    r3 = httpx.post(refresh_url, timeout=120.0)
    print(f"  refresh HTTP {r3.status_code}")

    print(f"\nDONE. Update tracker:")
    print(f"  - coordination/lane_state.json honest_operational_count.current_api_truth += 1")
    print(f"  - docs/PHASE2_PROGRESS.md §15 entry for {MUNI} {STATE}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
